name: bonfire
description: (RPG maker) Create RPG-style or similar games more simply with Flame.
version: 3.10.0
homepage: https://bonfire-engine.github.io
repository: https://github.com/RafaelBarbosatec/bonfire
issue_tracker: https://github.com/RafaelBarbosatec/bonfire/issues
# documentation: https://bonfire-engine.github.io

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter

  flame: 1.18.0
  tiledjsonreader: ^1.3.5
  http: ^1.2.2
  a_star_algorithm: ^0.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
